name: Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    name: build-app
    runs-on: ubuntu-latest

    env:
      COOKIE: ${{ secrets.COOKIE }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug environment
        run: |
          echo "COOKIE is set: $([[ -n "$COOKIE" ]] && echo "YES" || echo "NO")"
          echo "COOKIE length: ${#COOKIE}"
        env:
          COOKIE: ${{ secrets.COOKIE }}

      - name: Install bun
        uses: oven-sh/setup-bun@v2